services:
  nifi:
    image: apache/nifi:2.1.0
    container_name: nifi
    ports:
      - "18080:8080"
    volumes:
      - ./data:/opt/nifi/nifi-current
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_JVM_HEAP_MAX=2g