services:
  minio:
    image: minio/minio:latest
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - ./data:/data
      - ./config:/root/.minio
    command: server /data --console-address ":9000" -address ":9001"