services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=niubi
      - DOCKER_INFLUXDB_INIT_BUCKET=iot
#      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=testtoken
    volumes:
      - ./data/influxdb:/var/lib/influxdb2
	  
#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana
#    restart: unless-stopped
#    ports:
#      - "3000:3000"
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin123
#    volumes:
#      - ./data/grafana:/var/lib/grafana
#    depends_on:
#      - influxdb